import { IDictionary } from "../common.types";

/** used in restlets API */
export const nsCountriesByEnum = {
    _afghanistan: { code: 'AF', title: "Afghanistan" },
    _alandIslands: { code: 'AX', title: "Åland Islands" },
    _albania: { code: 'AL', title: "Albania" },
    _algeria: { code: 'DZ', title: "Algeria" },
    _americanSamoa: { code: 'AS', title: "American Samoa" },
    _andorra: { code: 'AD', title: "Andorra" },
    _angola: { code: 'AO', title: "Angola" },
    _anguilla: { code: 'AI', title: "Anguilla" },
    _antarctica: { code: 'AQ', title: "Antarctica" },
    _antiguaAndBarbuda: { code: 'AG', title: "Antigua and Barbuda" },
    _argentina: { code: 'AR', title: "Argentina" },
    _armenia: { code: 'AM', title: "Armenia" },
    _aruba: { code: 'AW', title: "Aruba" },
    _australia: { code: 'AU', title: "Australia" },
    _austria: { code: 'AT', title: "Austria" },
    _azerbaijan: { code: 'AZ', title: "Azerbaijan" },
    _bahamas: { code: 'BS', title: "Bahamas" },
    _bahrain: { code: 'BH', title: "Bahrain" },
    _bangladesh: { code: 'BD', title: "Bangladesh" },
    _barbados: { code: 'BB', title: "Barbados" },
    _belarus: { code: 'BY', title: "Belarus" },
    _belgium: { code: 'BE', title: "Belgium" },
    _belize: { code: 'BZ', title: "Belize" },
    _benin: { code: 'BJ', title: "Benin" },
    _bermuda: { code: 'BM', title: "Bermuda" },
    _bhutan: { code: 'BT', title: "Bhutan" },
    _boliviaPlurinationalStateOf: { code: 'BO', title: "Bolivia (Plurinational State of)" },
    _bonaireSaintEustatiusAndSaba: { code: 'BQ', title: "Bonaire, Sint Eustatius and Saba" },
    _bosniaAndHerzegovina: { code: 'BA', title: "Bosnia and Herzegovina" },
    _botswana: { code: 'BW', title: "Botswana" },
    _bouvetIsland: { code: 'BV', title: "Bouvet Island" },
    _brazil: { code: 'BR', title: "Brazil" },
    _britishIndianOceanTerritory: { code: 'IO', title: "British Indian Ocean Territory" },
    _bruneiDarussalam: { code: 'BN', title: "Brunei Darussalam" },
    _bulgaria: { code: 'BG', title: "Bulgaria" },
    _burkinaFaso: { code: 'BF', title: "Burkina Faso" },
    _burundi: { code: 'BI', title: "Burundi" },
    _caboVerde: { code: 'CV', title: "Cabo Verde" },
    _cambodia: { code: 'KH', title: "Cambodia" },
    _cameroon: { code: 'CM', title: "Cameroon" },
    _canada: { code: 'CA', title: "Canada" },
    _canaryIslands: { code: 'IC', title: "Canary Islands" },
    _caymanIslands: { code: 'KY', title: "Cayman Islands" },
    _centralAfricanRepublic: { code: 'CF', title: "Central African Republic" },
    _ceutaAndMelilla: { code: 'EA', title: "Ceuta and Melilla" },
    _chad: { code: 'TD', title: "Chad" },
    _chile: { code: 'CL', title: "Chile" },
    _china: { code: 'CN', title: "China" },
    _christmasIsland: { code: 'CX', title: "Christmas Island" },
    _cocosKeelingIslands: { code: 'CC', title: "Cocos (Keeling) Islands" },
    _colombia: { code: 'CO', title: "Colombia" },
    _comoros: { code: 'KM', title: "Comoros" },
    _congo: { code: 'CG', title: "Congo" },
    _congoTheDemocraticRepublicOfThe: { code: 'CD', title: "Congo (the Democratic Republic of the)" },
    _cookIslands: { code: 'CK', title: "Cook Islands" },
    _costaRica: { code: 'CR', title: "Costa Rica" },
    _coteDIvoire: { code: 'CI', title: "Côte d'Ivoire" },
    _croatia: { code: 'HR', title: "Croatia" },
    _cuba: { code: 'CU', title: "Cuba" },
    _curacao: { code: 'CW', title: "Curacao" },
    _cyprus: { code: 'CY', title: "Cyprus" },
    _czechia: { code: 'CZ', title: "Czechia" },
    _denmark: { code: 'DK', title: "Denmark" },
    _djibouti: { code: 'DJ', title: "Djibouti" },
    _dominica: { code: 'DM', title: "Dominica" },
    _dominicanRepublic: { code: 'DO', title: "Dominican Republic" },
    _ecuador: { code: 'EC', title: "Ecuador" },
    _egypt: { code: 'EG', title: "Egypt" },
    _elSalvador: { code: 'SV', title: "El Salvador" },
    _equatorialGuinea: { code: 'GQ', title: "Equatorial Guinea" },
    _eritrea: { code: 'ER', title: "Eritrea" },
    _estonia: { code: 'EE', title: "Estonia" },
    _eswatini: { code: 'SZ', title: "Eswatini" },
    _ethiopia: { code: 'ET', title: "Ethiopia" },
    _falklandIslandsMalvinas: { code: 'FK', title: "Falkland Islands (Malvinas)" },
    _faroeIslands: { code: 'FO', title: "Faroe Islands" },
    _fiji: { code: 'FJ', title: "Fiji" },
    _finland: { code: 'FI', title: "Finland" },
    _france: { code: 'FR', title: "France" },
    _frenchGuiana: { code: 'GF', title: "French Guiana" },
    _frenchPolynesia: { code: 'PF', title: "French Polynesia" },
    _frenchSouthernTerritories: { code: 'TF', title: "French Southern Territories" },
    _gabon: { code: 'GA', title: "Gabon" },
    _gambia: { code: 'GM', title: "Gambia" },
    _georgia: { code: 'GE', title: "Georgia" },
    _germany: { code: 'DE', title: "Germany" },
    _ghana: { code: 'GH', title: "Ghana" },
    _gibraltar: { code: 'GI', title: "Gibraltar" },
    _greece: { code: 'GR', title: "Greece" },
    _greenland: { code: 'GL', title: "Greenland" },
    _grenada: { code: 'GD', title: "Grenada" },
    _guadeloupe: { code: 'GP', title: "Guadeloupe" },
    _guam: { code: 'GU', title: "Guam" },
    _guatemala: { code: 'GT', title: "Guatemala" },
    _guernsey: { code: 'GG', title: "Guernsey" },
    _guinea: { code: 'GN', title: "Guinea" },
    _guineaBissau: { code: 'GW', title: "Guinea-Bissau" },
    _guyana: { code: 'GY', title: "Guyana" },
    _haiti: { code: 'HT', title: "Haiti" },
    _heardIslandAndMcDonaldIslands: { code: 'HM', title: "Heard Island and McDonald Islands" },
    _holySee: { code: 'VA', title: "Holy See" },
    _honduras: { code: 'HN', title: "Honduras" },
    _hongKong: { code: 'HK', title: "Hong Kong" },
    _hungary: { code: 'HU', title: "Hungary" },
    _iceland: { code: 'IS', title: "Iceland" },
    _india: { code: 'IN', title: "India" },
    _indonesia: { code: 'ID', title: "Indonesia" },
    _iranIslamicRepublicOf: { code: 'IR', title: "Iran (Islamic Republic of)" },
    _iraq: { code: 'IQ', title: "Iraq" },
    _ireland: { code: 'IE', title: "Ireland" },
    _isleOfMan: { code: 'IM', title: "Isle of Man" },
    _israel: { code: 'IL', title: "Israel" },
    _italy: { code: 'IT', title: "Italy" },
    _jamaica: { code: 'JM', title: "Jamaica" },
    _japan: { code: 'JP', title: "Japan" },
    _jersey: { code: 'JE', title: "Jersey" },
    _jordan: { code: 'JO', title: "Jordan" },
    _kazakhstan: { code: 'KZ', title: "Kazakhstan" },
    _kenya: { code: 'KE', title: "Kenya" },
    _kiribati: { code: 'KI', title: "Kiribati" },
    _koreaTheDemocraticPeoplesRepublicOf: { code: 'KP', title: "Korea (the Democratic People's Republic of)" },
    _koreaTheRepublicOf: { code: 'KR', title: "Korea (the Republic of)" },
    _kosovo: { code: 'XK', title: "Kosovo" },
    _kuwait: { code: 'KW', title: "Kuwait" },
    _kyrgyzstan: { code: 'KG', title: "Kyrgyzstan" },
    _laoPeoplesDemocraticRepublic: { code: 'LA', title: "Lao, People's Democratic Republic" },
    _latvia: { code: 'LV', title: "Latvia" },
    _lebanon: { code: 'LB', title: "Lebanon" },
    _lesotho: { code: 'LS', title: "Lesotho" },
    _liberia: { code: 'LR', title: "Liberia" },
    _libya: { code: 'LY', title: "Libya" },
    _liechtenstein: { code: 'LI', title: "Liechtenstein" },
    _lithuania: { code: 'LT', title: "Lithuania" },
    _luxembourg: { code: 'LU', title: "Luxembourg" },
    _macao: { code: 'MO', title: "Macao" },
    _madagascar: { code: 'MG', title: "Madagascar" },
    _malawi: { code: 'MW', title: "Malawi" },
    _malaysia: { code: 'MY', title: "Malaysia" },
    _maldives: { code: 'MV', title: "Maldives" },
    _mali: { code: 'ML', title: "Mali" },
    _malta: { code: 'MT', title: "Malta" },
    _marshallIslands: { code: 'MH', title: "Marshall Islands" },
    _martinique: { code: 'MQ', title: "Martinique" },
    _mauritania: { code: 'MR', title: "Mauritania" },
    _mauritius: { code: 'MU', title: "Mauritius" },
    _mayotte: { code: 'YT', title: "Mayotte" },
    _mexico: { code: 'MX', title: "Mexico" },
    _micronesiaFederalStatesOf: { code: 'FM', title: "Micronesia (Federated States of)" },
    _moldovaTheRepublicOf: { code: 'MD', title: "Moldova (the Republic of)" },
    _monaco: { code: 'MC', title: "Monaco" },
    _mongolia: { code: 'MN', title: "Mongolia" },
    _montenegro: { code: 'ME', title: "Montenegro" },
    _montserrat: { code: 'MS', title: "Montserrat" },
    _morocco: { code: 'MA', title: "Morocco" },
    _mozambique: { code: 'MZ', title: "Mozambique" },
    _myanmar: { code: 'MM', title: "Myanmar" },
    _namibia: { code: 'NA', title: "Namibia" },
    _nauru: { code: 'NR', title: "Nauru" },
    _nepal: { code: 'NP', title: "Nepal" },
    _netherlands: { code: 'NL', title: "Netherlands" },
    _newCaledonia: { code: 'NC', title: "New Caledonia" },
    _newZealand: { code: 'NZ', title: "New Zealand" },
    _nicaragua: { code: 'NI', title: "Nicaragua" },
    _niger: { code: 'NE', title: "Niger" },
    _nigeria: { code: 'NG', title: "Nigeria" },
    _niue: { code: 'NU', title: "Niue" },
    _norfolkIsland: { code: 'NF', title: "Norfolk Island" },
    _northernMarianaIslands: { code: 'MP', title: "Northern Mariana Islands" },
    _northMacedonia: { code: 'MK', title: "North Macedonia" },
    _norway: { code: 'NO', title: "Norway" },
    _oman: { code: 'OM', title: "Oman" },
    _pakistan: { code: 'PK', title: "Pakistan" },
    _palau: { code: 'PW', title: "Palau" },
    _palestineStateOf: { code: 'PS', title: "Palestine (State of)" },
    _panama: { code: 'PA', title: "Panama" },
    _papuaNewGuinea: { code: 'PG', title: "Papua New Guinea" },
    _paraguay: { code: 'PY', title: "Paraguay" },
    _peru: { code: 'PE', title: "Peru" },
    _philippines: { code: 'PH', title: "Philippines" },
    _pitcairn: { code: 'PN', title: "Pitcairn" },
    _poland: { code: 'PL', title: "Poland" },
    _portugal: { code: 'PT', title: "Portugal" },
    _puertoRico: { code: 'PR', title: "Puerto Rico" },
    _qatar: { code: 'QA', title: "Qatar" },
    _reunion: { code: 'RE', title: "Réunion" },
    _romania: { code: 'RO', title: "Romania" },
    _russianFederation: { code: 'RU', title: "Russian Federation" },
    _rwanda: { code: 'RW', title: "Rwanda" },
    _saintBarthelemy: { code: 'BL', title: "Saint Barthélemy" },
    _saintHelenaAscensionAndTristanDaCunha: { code: 'SH', title: "Saint Helena, Ascension and Tristan da Cunha" },
    _saintKittsAndNevis: { code: 'KN', title: "Saint Kitts and Nevis" },
    _saintLucia: { code: 'LC', title: "Saint Lucia" },
    _saintMartinFrenchPart: { code: 'MF', title: "Saint Martin (French part)" },
    _saintPierreAndMiquelon: { code: 'PM', title: "Saint Pierre and Miquelon" },
    _saintVincentAndTheGrenadines: { code: 'VC', title: "Saint Vincent and the Grenadines" },
    _samoa: { code: 'WS', title: "Samoa" },
    _sanMarino: { code: 'SM', title: "San Marino" },
    _saoTomeAndPrincipe: { code: 'ST', title: "Sao Tome and Principe" },
    _saudiArabia: { code: 'SA', title: "Saudi Arabia" },
    _senegal: { code: 'SN', title: "Senegal" },
    _serbia: { code: 'RS', title: "Serbia" },
    _seychelles: { code: 'SC', title: "Seychelles" },
    _sierraLeone: { code: 'SL', title: "Sierra Leone" },
    _singapore: { code: 'SG', title: "Singapore" },
    _sintMaartenDutchPart: { code: 'SX', title: "Sint Maarten (Dutch part)" },
    _slovakia: { code: 'SK', title: "Slovakia" },
    _slovenia: { code: 'SI', title: "Slovenia" },
    _solomonIslands: { code: 'SB', title: "Solomon Islands" },
    _somalia: { code: 'SO', title: "Somalia" },
    _southAfrica: { code: 'ZA', title: "South Africa" },
    _southGeorgiaAndTheSouthSandwichIslands: { code: 'GS', title: "South Georgia and the South Sandwich Islands" },
    _southSudan: { code: 'SS', title: "South Sudan" },
    _spain: { code: 'ES', title: "Spain" },
    _sriLanka: { code: 'LK', title: "Sri Lanka" },
    _sudan: { code: 'SD', title: "Sudan" },
    _suriname: { code: 'SR', title: "Suriname" },
    _svalbardAndJanMayen: { code: 'SJ', title: "Svalbard and Jan Mayen" },
    _sweden: { code: 'SE', title: "Sweden" },
    _switzerland: { code: 'CH', title: "Switzerland" },
    _syrianArabRepublic: { code: 'SY', title: "Syrian Arab Republic" },
    _taiwan: { code: 'TW', title: "Taiwan (Province of China)" },
    _tajikistan: { code: 'TJ', title: "Tajikistan" },
    _tanzaniaTheUnitedRepublicOf: { code: 'TZ', title: "Tanzania, the United Republic of" },
    _thailand: { code: 'TH', title: "Thailand" },
    _timorLeste: { code: 'TL', title: "Timor-Leste" },
    _togo: { code: 'TG', title: "Togo" },
    _tokelau: { code: 'TK', title: "Tokelau" },
    _tonga: { code: 'TO', title: "Tonga" },
    _trinidadAndTobago: { code: 'TT', title: "Trinidad and Tobago" },
    _tunisia: { code: 'TN', title: "Tunisia" },
    _turkiye: { code: 'TR', title: "Türkiye" },
    _turkmenistan: { code: 'TM', title: "Turkmenistan" },
    _turksAndCaicosIslands: { code: 'TC', title: "Turks and Caicos Islands" },
    _tuvalu: { code: 'TV', title: "Tuvalu" },
    _uganda: { code: 'UG', title: "Uganda" },
    _ukraine: { code: 'UA', title: "Ukraine" },
    _unitedArabEmirates: { code: 'AE', title: "United Arab Emirates" },
    _unitedKingdom: { code: 'GB', title: "United Kingdom" },
    _unitedStates: { code: 'US', title: "United States" },
    _unitedStatesMinorOutlyingIslands: { code: 'UM', title: "United States Minor Outlying Islands" },
    _uruguay: { code: 'UY', title: "Uruguay" },
    _uzbekistan: { code: 'UZ', title: "Uzbekistan" },
    _vanuatu: { code: 'VU', title: "Vanuatu" },
    _venezuelaBolivarianRepublicOf: { code: 'VE', title: "Venezuela (Bolivarian Republic of)" },
    _vietnam: { code: 'VN', title: "Viet Nam" },
    _virginIslandsBritish: { code: 'VG', title: "Virgin Islands (British)" },
    _virginIslandsUS: { code: 'VI', title: "Virgin Islands (U.S.)" },
    _wallisAndFutunaIslands: { code: 'WF', title: "Wallis and Futuna Islands" },
    _westernSahara: { code: 'EH', title: "Western Sahara" },
    _yemen: { code: 'YE', title: "Yemen" },
    _zambia: { code: 'ZM', title: "Zambia" },
    _zimbabwe: { code: 'ZW', title: "Zimbabwe" }
} as const satisfies IDictionary<{ code: string; title: string; }>
export type tnsCountryEnum = keyof typeof nsCountriesByEnum;