import { IDictionary } from "../common.types";

/** used in REST API */
export const nsCountriesByCode = {
    AF: { enum: '_afghanistan', title: "Afghanistan" },
    AX: { enum: '_alandIslands', title: "Åland Islands" },
    AL: { enum: '_albania', title: "Albania" },
    DZ: { enum: '_algeria', title: "Algeria" },
    AS: { enum: '_americanSamoa', title: "American Samoa" },
    AD: { enum: '_andorra', title: "Andorra" },
    AO: { enum: '_angola', title: "Angola" },
    AI: { enum: '_anguilla', title: "Anguilla" },
    AQ: { enum: '_antarctica', title: "Antarctica" },
    AG: { enum: '_antiguaAndBarbuda', title: "Antigua and Barbuda" },
    AR: { enum: '_argentina', title: "Argentina" },
    AM: { enum: '_armenia', title: "Armenia" },
    AW: { enum: '_aruba', title: "Aruba" },
    AU: { enum: '_australia', title: "Australia" },
    AT: { enum: '_austria', title: "Austria" },
    AZ: { enum: '_azerbaijan', title: "Azerbaijan" },
    BS: { enum: '_bahamas', title: "Bahamas" },
    BH: { enum: '_bahrain', title: "Bahrain" },
    BD: { enum: '_bangladesh', title: "Bangladesh" },
    BB: { enum: '_barbados', title: "Barbados" },
    BY: { enum: '_belarus', title: "Belarus" },
    BE: { enum: '_belgium', title: "Belgium" },
    BZ: { enum: '_belize', title: "Belize" },
    BJ: { enum: '_benin', title: "Benin" },
    BM: { enum: '_bermuda', title: "Bermuda" },
    BT: { enum: '_bhutan', title: "Bhutan" },
    BO: { enum: '_boliviaPlurinationalStateOf', title: "Bolivia (Plurinational State of)" },
    BQ: { enum: '_bonaireSaintEustatiusAndSaba', title: "Bonaire, Sint Eustatius and Saba" },
    BA: { enum: '_bosniaAndHerzegovina', title: "Bosnia and Herzegovina" },
    BW: { enum: '_botswana', title: "Botswana" },
    BV: { enum: '_bouvetIsland', title: "Bouvet Island" },
    BR: { enum: '_brazil', title: "Brazil" },
    IO: { enum: '_britishIndianOceanTerritory', title: "British Indian Ocean Territory" },
    BN: { enum: '_bruneiDarussalam', title: "Brunei Darussalam" },
    BG: { enum: '_bulgaria', title: "Bulgaria" },
    BF: { enum: '_burkinaFaso', title: "Burkina Faso" },
    BI: { enum: '_burundi', title: "Burundi" },
    CV: { enum: '_caboVerde', title: "Cabo Verde" },
    KH: { enum: '_cambodia', title: "Cambodia" },
    CM: { enum: '_cameroon', title: "Cameroon" },
    CA: { enum: '_canada', title: "Canada" },
    IC: { enum: '_canaryIslands', title: "Canary Islands" },
    KY: { enum: '_caymanIslands', title: "Cayman Islands" },
    CF: { enum: '_centralAfricanRepublic', title: "Central African Republic" },
    EA: { enum: '_ceutaAndMelilla', title: "Ceuta and Melilla" },
    TD: { enum: '_chad', title: "Chad" },
    CL: { enum: '_chile', title: "Chile" },
    CN: { enum: '_china', title: "China" },
    CX: { enum: '_christmasIsland', title: "Christmas Island" },
    CC: { enum: '_cocosKeelingIslands', title: "Cocos (Keeling) Islands" },
    CO: { enum: '_colombia', title: "Colombia" },
    KM: { enum: '_comoros', title: "Comoros" },
    CG: { enum: '_congo', title: "Congo" },
    CD: { enum: '_congoTheDemocraticRepublicOfThe', title: "Congo (the Democratic Republic of the)" },
    CK: { enum: '_cookIslands', title: "Cook Islands" },
    CR: { enum: '_costaRica', title: "Costa Rica" },
    CI: { enum: '_coteDIvoire', title: "Côte d'Ivoire" },
    HR: { enum: '_croatia', title: "Croatia" },
    CU: { enum: '_cuba', title: "Cuba" },
    CW: { enum: '_curacao', title: "Curacao" },
    CY: { enum: '_cyprus', title: "Cyprus" },
    CZ: { enum: '_czechia', title: "Czechia" },
    DK: { enum: '_denmark', title: "Denmark" },
    DJ: { enum: '_djibouti', title: "Djibouti" },
    DM: { enum: '_dominica', title: "Dominica" },
    DO: { enum: '_dominicanRepublic', title: "Dominican Republic" },
    EC: { enum: '_ecuador', title: "Ecuador" },
    EG: { enum: '_egypt', title: "Egypt" },
    SV: { enum: '_elSalvador', title: "El Salvador" },
    GQ: { enum: '_equatorialGuinea', title: "Equatorial Guinea" },
    ER: { enum: '_eritrea', title: "Eritrea" },
    EE: { enum: '_estonia', title: "Estonia" },
    SZ: { enum: '_eswatini', title: "Eswatini" },
    ET: { enum: '_ethiopia', title: "Ethiopia" },
    FK: { enum: '_falklandIslandsMalvinas', title: "Falkland Islands (Malvinas)" },
    FO: { enum: '_faroeIslands', title: "Faroe Islands" },
    FJ: { enum: '_fiji', title: "Fiji" },
    FI: { enum: '_finland', title: "Finland" },
    FR: { enum: '_france', title: "France" },
    GF: { enum: '_frenchGuiana', title: "French Guiana" },
    PF: { enum: '_frenchPolynesia', title: "French Polynesia" },
    TF: { enum: '_frenchSouthernTerritories', title: "French Southern Territories" },
    GA: { enum: '_gabon', title: "Gabon" },
    GM: { enum: '_gambia', title: "Gambia" },
    GE: { enum: '_georgia', title: "Georgia" },
    DE: { enum: '_germany', title: "Germany" },
    GH: { enum: '_ghana', title: "Ghana" },
    GI: { enum: '_gibraltar', title: "Gibraltar" },
    GR: { enum: '_greece', title: "Greece" },
    GL: { enum: '_greenland', title: "Greenland" },
    GD: { enum: '_grenada', title: "Grenada" },
    GP: { enum: '_guadeloupe', title: "Guadeloupe" },
    GU: { enum: '_guam', title: "Guam" },
    GT: { enum: '_guatemala', title: "Guatemala" },
    GG: { enum: '_guernsey', title: "Guernsey" },
    GN: { enum: '_guinea', title: "Guinea" },
    GW: { enum: '_guineaBissau', title: "Guinea-Bissau" },
    GY: { enum: '_guyana', title: "Guyana" },
    HT: { enum: '_haiti', title: "Haiti" },
    HM: { enum: '_heardIslandAndMcDonaldIslands', title: "Heard Island and McDonald Islands" },
    VA: { enum: '_holySee', title: "Holy See" },
    HN: { enum: '_honduras', title: "Honduras" },
    HK: { enum: '_hongKong', title: "Hong Kong" },
    HU: { enum: '_hungary', title: "Hungary" },
    IS: { enum: '_iceland', title: "Iceland" },
    IN: { enum: '_india', title: "India" },
    ID: { enum: '_indonesia', title: "Indonesia" },
    IR: { enum: '_iranIslamicRepublicOf', title: "Iran (Islamic Republic of)" },
    IQ: { enum: '_iraq', title: "Iraq" },
    IE: { enum: '_ireland', title: "Ireland" },
    IM: { enum: '_isleOfMan', title: "Isle of Man" },
    IL: { enum: '_israel', title: "Israel" },
    IT: { enum: '_italy', title: "Italy" },
    JM: { enum: '_jamaica', title: "Jamaica" },
    JP: { enum: '_japan', title: "Japan" },
    JE: { enum: '_jersey', title: "Jersey" },
    JO: { enum: '_jordan', title: "Jordan" },
    KZ: { enum: '_kazakhstan', title: "Kazakhstan" },
    KE: { enum: '_kenya', title: "Kenya" },
    KI: { enum: '_kiribati', title: "Kiribati" },
    KP: { enum: '_koreaTheDemocraticPeoplesRepublicOf', title: "Korea (the Democratic People's Republic of)" },
    KR: { enum: '_koreaTheRepublicOf', title: "Korea (the Republic of)" },
    XK: { enum: '_kosovo', title: "Kosovo" },
    KW: { enum: '_kuwait', title: "Kuwait" },
    KG: { enum: '_kyrgyzstan', title: "Kyrgyzstan" },
    LA: { enum: '_laoPeoplesDemocraticRepublic', title: "Lao, People's Democratic Republic" },
    LV: { enum: '_latvia', title: "Latvia" },
    LB: { enum: '_lebanon', title: "Lebanon" },
    LS: { enum: '_lesotho', title: "Lesotho" },
    LR: { enum: '_liberia', title: "Liberia" },
    LY: { enum: '_libya', title: "Libya" },
    LI: { enum: '_liechtenstein', title: "Liechtenstein" },
    LT: { enum: '_lithuania', title: "Lithuania" },
    LU: { enum: '_luxembourg', title: "Luxembourg" },
    MO: { enum: '_macao', title: "Macao" },
    MG: { enum: '_madagascar', title: "Madagascar" },
    MW: { enum: '_malawi', title: "Malawi" },
    MY: { enum: '_malaysia', title: "Malaysia" },
    MV: { enum: '_maldives', title: "Maldives" },
    ML: { enum: '_mali', title: "Mali" },
    MT: { enum: '_malta', title: "Malta" },
    MH: { enum: '_marshallIslands', title: "Marshall Islands" },
    MQ: { enum: '_martinique', title: "Martinique" },
    MR: { enum: '_mauritania', title: "Mauritania" },
    MU: { enum: '_mauritius', title: "Mauritius" },
    YT: { enum: '_mayotte', title: "Mayotte" },
    MX: { enum: '_mexico', title: "Mexico" },
    FM: { enum: '_micronesiaFederalStatesOf', title: "Micronesia (Federated States of)" },
    MD: { enum: '_moldovaTheRepublicOf', title: "Moldova (the Republic of)" },
    MC: { enum: '_monaco', title: "Monaco" },
    MN: { enum: '_mongolia', title: "Mongolia" },
    ME: { enum: '_montenegro', title: "Montenegro" },
    MS: { enum: '_montserrat', title: "Montserrat" },
    MA: { enum: '_morocco', title: "Morocco" },
    MZ: { enum: '_mozambique', title: "Mozambique" },
    MM: { enum: '_myanmar', title: "Myanmar" },
    NA: { enum: '_namibia', title: "Namibia" },
    NR: { enum: '_nauru', title: "Nauru" },
    NP: { enum: '_nepal', title: "Nepal" },
    NL: { enum: '_netherlands', title: "Netherlands" },
    NC: { enum: '_newCaledonia', title: "New Caledonia" },
    NZ: { enum: '_newZealand', title: "New Zealand" },
    NI: { enum: '_nicaragua', title: "Nicaragua" },
    NE: { enum: '_niger', title: "Niger" },
    NG: { enum: '_nigeria', title: "Nigeria" },
    NU: { enum: '_niue', title: "Niue" },
    NF: { enum: '_norfolkIsland', title: "Norfolk Island" },
    MP: { enum: '_northernMarianaIslands', title: "Northern Mariana Islands" },
    MK: { enum: '_northMacedonia', title: "North Macedonia" },
    NO: { enum: '_norway', title: "Norway" },
    OM: { enum: '_oman', title: "Oman" },
    PK: { enum: '_pakistan', title: "Pakistan" },
    PW: { enum: '_palau', title: "Palau" },
    PS: { enum: '_palestineStateOf', title: "Palestine (State of)" },
    PA: { enum: '_panama', title: "Panama" },
    PG: { enum: '_papuaNewGuinea', title: "Papua New Guinea" },
    PY: { enum: '_paraguay', title: "Paraguay" },
    PE: { enum: '_peru', title: "Peru" },
    PH: { enum: '_philippines', title: "Philippines" },
    PN: { enum: '_pitcairn', title: "Pitcairn" },
    PL: { enum: '_poland', title: "Poland" },
    PT: { enum: '_portugal', title: "Portugal" },
    PR: { enum: '_puertoRico', title: "Puerto Rico" },
    QA: { enum: '_qatar', title: "Qatar" },
    RE: { enum: '_reunion', title: "Réunion" },
    RO: { enum: '_romania', title: "Romania" },
    RU: { enum: '_russianFederation', title: "Russian Federation" },
    RW: { enum: '_rwanda', title: "Rwanda" },
    BL: { enum: '_saintBarthelemy', title: "Saint Barthélemy" },
    SH: { enum: '_saintHelenaAscensionAndTristanDaCunha', title: "Saint Helena, Ascension and Tristan da Cunha" },
    KN: { enum: '_saintKittsAndNevis', title: "Saint Kitts and Nevis" },
    LC: { enum: '_saintLucia', title: "Saint Lucia" },
    MF: { enum: '_saintMartinFrenchPart', title: "Saint Martin (French part)" },
    PM: { enum: '_saintPierreAndMiquelon', title: "Saint Pierre and Miquelon" },
    VC: { enum: '_saintVincentAndTheGrenadines', title: "Saint Vincent and the Grenadines" },
    WS: { enum: '_samoa', title: "Samoa" },
    SM: { enum: '_sanMarino', title: "San Marino" },
    ST: { enum: '_saoTomeAndPrincipe', title: "Sao Tome and Principe" },
    SA: { enum: '_saudiArabia', title: "Saudi Arabia" },
    SN: { enum: '_senegal', title: "Senegal" },
    RS: { enum: '_serbia', title: "Serbia" },
    SC: { enum: '_seychelles', title: "Seychelles" },
    SL: { enum: '_sierraLeone', title: "Sierra Leone" },
    SG: { enum: '_singapore', title: "Singapore" },
    SX: { enum: '_sintMaartenDutchPart', title: "Sint Maarten (Dutch part)" },
    SK: { enum: '_slovakia', title: "Slovakia" },
    SI: { enum: '_slovenia', title: "Slovenia" },
    SB: { enum: '_solomonIslands', title: "Solomon Islands" },
    SO: { enum: '_somalia', title: "Somalia" },
    ZA: { enum: '_southAfrica', title: "South Africa" },
    GS: { enum: '_southGeorgiaAndTheSouthSandwichIslands', title: "South Georgia and the South Sandwich Islands" },
    SS: { enum: '_southSudan', title: "South Sudan" },
    ES: { enum: '_spain', title: "Spain" },
    LK: { enum: '_sriLanka', title: "Sri Lanka" },
    SD: { enum: '_sudan', title: "Sudan" },
    SR: { enum: '_suriname', title: "Suriname" },
    SJ: { enum: '_svalbardAndJanMayen', title: "Svalbard and Jan Mayen" },
    SE: { enum: '_sweden', title: "Sweden" },
    CH: { enum: '_switzerland', title: "Switzerland" },
    SY: { enum: '_syrianArabRepublic', title: "Syrian Arab Republic" },
    TW: { enum: '_taiwan', title: "Taiwan (Province of China)" },
    TJ: { enum: '_tajikistan', title: "Tajikistan" },
    TZ: { enum: '_tanzaniaTheUnitedRepublicOf', title: "Tanzania, the United Republic of" },
    TH: { enum: '_thailand', title: "Thailand" },
    TL: { enum: '_timorLeste', title: "Timor-Leste" },
    TG: { enum: '_togo', title: "Togo" },
    TK: { enum: '_tokelau', title: "Tokelau" },
    TO: { enum: '_tonga', title: "Tonga" },
    TT: { enum: '_trinidadAndTobago', title: "Trinidad and Tobago" },
    TN: { enum: '_tunisia', title: "Tunisia" },
    TR: { enum: '_turkiye', title: "Türkiye" },
    TM: { enum: '_turkmenistan', title: "Turkmenistan" },
    TC: { enum: '_turksAndCaicosIslands', title: "Turks and Caicos Islands" },
    TV: { enum: '_tuvalu', title: "Tuvalu" },
    UG: { enum: '_uganda', title: "Uganda" },
    UA: { enum: '_ukraine', title: "Ukraine" },
    AE: { enum: '_unitedArabEmirates', title: "United Arab Emirates" },
    GB: { enum: '_unitedKingdom', title: "United Kingdom" },
    US: { enum: '_unitedStates', title: "United States" },
    UM: { enum: '_unitedStatesMinorOutlyingIslands', title: "United States Minor Outlying Islands" },
    UY: { enum: '_uruguay', title: "Uruguay" },
    UZ: { enum: '_uzbekistan', title: "Uzbekistan" },
    VU: { enum: '_vanuatu', title: "Vanuatu" },
    VE: { enum: '_venezuelaBolivarianRepublicOf', title: "Venezuela (Bolivarian Republic of)" },
    VN: { enum: '_vietnam', title: "Viet Nam" },
    VG: { enum: '_virginIslandsBritish', title: "Virgin Islands (British)" },
    VI: { enum: '_virginIslandsUS', title: "Virgin Islands (U.S.)" },
    WF: { enum: '_wallisAndFutunaIslands', title: "Wallis and Futuna Islands" },
    EH: { enum: '_westernSahara', title: "Western Sahara" },
    YE: { enum: '_yemen', title: "Yemen" },
    ZM: { enum: '_zambia', title: "Zambia" },
    ZW: { enum: '_zimbabwe', title: "Zimbabwe" }
} as const satisfies IDictionary<{ enum: string; title: string; }>;
export type tnsCountryCode = keyof typeof nsCountriesByCode;
